name: sondreb/action-release-download
description: |
  GitHub Release Action
author: Sondre Bjellås
branding:
  icon: box
  color: gray-dark
inputs:
  token:
    description: 'The GitHub token.'
    required: true
    default: ''
  url:
    description: 'URL to assets JSON.'
    required: true
    default: ''
  folder:
    required: false
    default: ''
  verbose:
    required: false
    default: 'false'
runs:
  using: node12
  main: action.js